### PR TITLE
BUGFIX: wrong filename "hpyh-it.tex"

### PR DESCRIPTION
**Pull request by manumaticx**
This is a backport of https://github.com/nikitadol/hyphenator/pull/11

### CODE REVIEW

**Comment by manumaticx** [comment]
@impure can you please release a new version after merging this?

see: https://github.com/impure/auto_hyphenating_text/issues/15

**Comment by manumaticx** [comment]
Hey @impure 

Can you please publish a new version of the package? 

Thanks :)

**Comment by impure** [comment]
Is it not working after pub upgrade?

**Comment by manumaticx** [comment]
The [version](https://github.com/impure/hyphenator/blob/master/pubspec.yaml#L3) ist still 0.1.3, so afaik pub upgrade won't do anything.

I think you will have to publish a 0.1.4 version to pub.dev. But I'm not sure if you also have to update the dependency here: https://github.com/impure/auto_hyphenating_text/blob/main/pubspec.yaml#L17

**Pull request merged**
